name: Tests

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Install package in editable mode
        run: uv pip install -e .

      - name: Test with pytest
        run: uv run pytest --junitxml=pytest.xml --cov=merkle_zeppelin | tee pytest-result.txt

      - name: Make comment with test coverage
        uses: MishaKav/pytest-coverage-comment@v1.1.54
        if: github.event_name != 'dependabot[bot]'
        with:
          pytest-coverage-path: ./pytest-result.txt
          junitxml-path: ./pytest.xml
